from pathlib import Path

from docx import Document

from src.report_generator import generate_report
from src.schemas import (
    BilingualPair,
    DocumentMetadata,
    PairStatus,
    ProcessingResult,
    ProcessingSettings,
)


def test_report_generator_creates_expected_sections(tmp_path: Path):
    result = ProcessingResult(
        metadata=DocumentMetadata(filename="sample.pdf", file_type="pdf", page_count=1),
        settings=ProcessingSettings(dry_run=True),
        blocks=[],
        pairs=[
            BilingualPair(
                pair_id="p1",
                page=1,
                section="1.0",
                chinese_text="质量管理体系",
                machine_translated_english="Quality Management System",
                english_text="Quality Management System",
                chinese_block_id="zh",
                english_block_id="en",
                pair_confidence=0.9,
                semantic_similarity=1.0,
                final_pair_score=0.9,
                pairing_reason="test",
                pair_status=PairStatus.confirmed,
                should_check_translation=False,
            )
        ],
        regulations=[],
    )
    output = generate_report(result, tmp_path / "report.docx")
    assert output.exists()
    assert [path.name for path in tmp_path.iterdir()] == ["report.docx"]
    document = Document(output)
    text = "\n".join(paragraph.text for paragraph in document.paragraphs)
    assert "Executive summary" in text
    assert "Translation equivalence findings" in text
    assert "Unpaired / uncertain blocks for manual review" in text
    assert "Full bilingual pair list" not in text
    assert "This report is generated by an AI-assisted tool" in text
