from __future__ import annotations

import json
from typing import Any

from rapidfuzz import fuzz

from .llm_client import call_llm_json, format_api_error, get_llm_config
from .utils import BilingualPair, DocumentResult, TextBlock, confidence_from_score, contains_chinese, contains_english, normalize_text


def identify_bilingual_pairs_with_api(
    doc: DocumentResult,
    deterministic_pairs: list[BilingualPair],
    model: str,
) -> tuple[list[BilingualPair], list[str]]:
    warnings: list[str] = []
    config = get_llm_config(model)
    if not config.api_key:
        return deterministic_pairs, [f"{config.provider} API key not found. Part C used deterministic pairing only."]

    candidate_blocks = _candidate_blocks(doc.blocks)
    if not candidate_blocks:
        return deterministic_pairs, [f"{doc.file_name}: no Chinese/English candidate blocks found for API pairing."]

    payload = {
        "task": "Identify Chinese-English translation pairs in a bilingual regulatory or quality-management document. Chinese is controlling.",
        "rules": [
            "Pair Chinese source text with the English translation that most likely corresponds to it.",
            "Use nearby blocks, table rows, mixed Chinese-English blocks, headings, and page/section location.",
            "Return only likely translation pairs. Do not invent text.",
            "Confidence must be High, Medium, or Low.",
            "Return JSON array only.",
        ],
        "output_schema": {
            "pair_id": "string",
            "chinese_text": "string",
            "english_text": "string",
            "confidence": "High, Medium, or Low",
            "confidence_score": "number between 0 and 1",
            "pairing_reason": "string",
            "location": "string",
            "chinese_block_id": "string",
            "english_block_id": "string",
        },
        "blocks": [
            {
                "block_id": block.block_id,
                "order": block.order,
                "location": block.location_label(),
                "page_number": block.page_number,
                "section_heading": block.section_heading,
                "block_type": block.block_type,
                "text": block.text,
            }
            for block in candidate_blocks
        ],
    }
    try:
        parsed = call_llm_json(
            config,
            [
                {
                    "role": "system",
                    "content": "You are an expert bilingual document alignment engine for Chinese-English medical-device regulatory documents.",
                },
                {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
            ],
            expected="array",
        )
    except Exception as exc:
        return deterministic_pairs, [f"{doc.file_name}: API pairing failed, so deterministic pairing was used. {format_api_error(config.provider, exc)}"]

    api_pairs = _parse_api_pairs(parsed, doc, candidate_blocks)
    if not api_pairs:
        return deterministic_pairs, [f"{doc.file_name}: API pairing returned no usable pairs, so deterministic pairing was used."]
    warnings.append(f"{doc.file_name}: Part C pairs generated by {config.provider} API using model {config.model}.")
    return api_pairs, warnings


def _candidate_blocks(blocks: list[TextBlock]) -> list[TextBlock]:
    return [block for block in blocks if contains_chinese(block.text) or contains_english(block.text)]


def _parse_api_pairs(items: Any, doc: DocumentResult, blocks: list[TextBlock]) -> list[BilingualPair]:
    block_by_id = {block.block_id: block for block in blocks}
    pairs: list[BilingualPair] = []
    seen: set[tuple[str, str]] = set()
    for idx, item in enumerate(items if isinstance(items, list) else []):
        zh = normalize_text(str(item.get("chinese_text", "")))
        en = normalize_text(str(item.get("english_text", "")))
        if not zh or not en:
            continue
        key = (zh[:120], en[:120])
        if key in seen:
            continue
        seen.add(key)
        zh_block = block_by_id.get(str(item.get("chinese_block_id", ""))) or _match_block_by_text(zh, blocks)
        en_block = block_by_id.get(str(item.get("english_block_id", ""))) or _match_block_by_text(en, blocks)
        try:
            score = float(item.get("confidence_score", 0.7))
        except (TypeError, ValueError):
            score = 0.7
        confidence = str(item.get("confidence") or confidence_from_score(score))
        pairs.append(
            BilingualPair(
                pair_id=f"{doc.file_name}:api-pair:{idx + 1}",
                file_name=doc.file_name,
                chinese_text=zh,
                english_text=en,
                confidence=confidence,
                confidence_score=round(max(0.0, min(score, 1.0)), 2),
                pairing_reason=f"API pairing: {item.get('pairing_reason', '')}".strip(),
                location=str(item.get("location") or (zh_block.location_label() if zh_block else "")),
                page_number=(zh_block.page_number if zh_block else None) or (en_block.page_number if en_block else None),
                section_heading=(zh_block.section_heading if zh_block else None) or (en_block.section_heading if en_block else None),
                chinese_block_id=zh_block.block_id if zh_block else str(item.get("chinese_block_id") or ""),
                english_block_id=en_block.block_id if en_block else str(item.get("english_block_id") or ""),
            )
        )
    return pairs


def _match_block_by_text(text: str, blocks: list[TextBlock]) -> TextBlock | None:
    """Recover source block metadata when the API omits or alters block IDs."""
    clean = normalize_text(text)
    if not clean:
        return None
    for block in blocks:
        block_text = normalize_text(block.text)
        if clean in block_text or block_text in clean:
            return block

    best_block: TextBlock | None = None
    best_score = 0
    needle = clean[:300]
    for block in blocks:
        score = fuzz.partial_ratio(needle, normalize_text(block.text)[:500])
        if score > best_score:
            best_block = block
            best_score = score
    return best_block if best_score >= 82 else None
