from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Iterable

from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from src.regulatory_checker import build_regulatory_coverage_matrix
from src.schemas import ProcessingResult, Severity
from src.utils import compact_context

DISCLAIMER = (
    "This report is generated by an AI-assisted tool for preliminary translation and "
    "regulatory consistency review. It does not constitute legal, regulatory, "
    "certification, or notified-body advice. Final decisions must be made by qualified "
    "regulatory and quality professionals."
)

COLORS = {
    "navy": "19324A",
    "blue": "2E74B5",
    "light_blue": "E8F0F7",
    "light_gray": "F2F4F7",
    "muted": "667085",
    "Critical": "FECACA",
    "Major": "FED7AA",
    "Minor": "DBEAFE",
    "Observation": "E5E7EB",
}


def _set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shading = tc_pr.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        tc_pr.append(shading)
    shading.set(qn("w:fill"), fill)


def _set_cell_margins(cell, top=80, start=120, bottom=80, end=120):
    tc = cell._tc
    tc_pr = tc.get_or_add_tcPr()
    tc_mar = tc_pr.first_child_found_in("w:tcMar")
    if tc_mar is None:
        tc_mar = OxmlElement("w:tcMar")
        tc_pr.append(tc_mar)
    for tag, value in (("top", top), ("start", start), ("bottom", bottom), ("end", end)):
        node = tc_mar.find(qn(f"w:{tag}"))
        if node is None:
            node = OxmlElement(f"w:{tag}")
            tc_mar.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def _set_repeat_table_header(row) -> None:
    tr_pr = row._tr.get_or_add_trPr()
    tbl_header = OxmlElement("w:tblHeader")
    tbl_header.set(qn("w:val"), "true")
    tr_pr.append(tbl_header)


def _set_table_geometry(table, widths_inches: list[float]) -> None:
    table.autofit = False
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table_width = int(sum(widths_inches) * 1440)
    tbl_pr = table._tbl.tblPr
    tbl_w = tbl_pr.find(qn("w:tblW"))
    if tbl_w is None:
        tbl_w = OxmlElement("w:tblW")
        tbl_pr.append(tbl_w)
    tbl_w.set(qn("w:w"), str(table_width))
    tbl_w.set(qn("w:type"), "dxa")
    tbl_ind = tbl_pr.find(qn("w:tblInd"))
    if tbl_ind is None:
        tbl_ind = OxmlElement("w:tblInd")
        tbl_pr.append(tbl_ind)
    tbl_ind.set(qn("w:w"), "120")
    tbl_ind.set(qn("w:type"), "dxa")

    grid = table._tbl.tblGrid
    for child in list(grid):
        grid.remove(child)
    for width in widths_inches:
        col = OxmlElement("w:gridCol")
        col.set(qn("w:w"), str(int(width * 1440)))
        grid.append(col)
    for row in table.rows:
        for index, cell in enumerate(row.cells):
            width_dxa = int(widths_inches[min(index, len(widths_inches) - 1)] * 1440)
            tc_pr = cell._tc.get_or_add_tcPr()
            tc_w = tc_pr.find(qn("w:tcW"))
            if tc_w is None:
                tc_w = OxmlElement("w:tcW")
                tc_pr.append(tc_w)
            tc_w.set(qn("w:w"), str(width_dxa))
            tc_w.set(qn("w:type"), "dxa")
            _set_cell_margins(cell)
            cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER


def _font_run(run, size=9, bold=False, color="000000", east_asia="Microsoft YaHei"):
    run.font.name = "Arial"
    run._element.get_or_add_rPr().rFonts.set(qn("w:ascii"), "Arial")
    run._element.get_or_add_rPr().rFonts.set(qn("w:hAnsi"), "Arial")
    run._element.get_or_add_rPr().rFonts.set(qn("w:eastAsia"), east_asia)
    run.font.size = Pt(size)
    run.bold = bold
    run.font.color.rgb = RGBColor.from_string(color)


def _set_paragraph_text(paragraph, text: str, *, size=8.5, bold=False, color="000000"):
    paragraph.clear()
    paragraph.paragraph_format.space_before = Pt(0)
    paragraph.paragraph_format.space_after = Pt(2)
    paragraph.paragraph_format.line_spacing = 1.05
    run = paragraph.add_run(str(text or ""))
    _font_run(run, size=size, bold=bold, color=color)


def _add_table(
    doc: Document,
    headers: list[str],
    rows: Iterable[list[str]],
    widths: list[float],
    *,
    font_size: float = 7.5,
    severity_column: int | None = None,
):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    header = table.rows[0]
    _set_repeat_table_header(header)
    for index, label in enumerate(headers):
        _set_cell_shading(header.cells[index], COLORS["navy"])
        _set_paragraph_text(
            header.cells[index].paragraphs[0],
            label,
            size=7.4,
            bold=True,
            color="FFFFFF",
        )
    for row_values in rows:
        cells = table.add_row().cells
        for index, value in enumerate(row_values):
            _set_paragraph_text(cells[index].paragraphs[0], value, size=font_size)
        if severity_column is not None and severity_column < len(cells):
            severity = str(row_values[severity_column])
            _set_cell_shading(cells[severity_column], COLORS.get(severity, "FFFFFF"))
    _set_table_geometry(table, widths)
    doc.add_paragraph().paragraph_format.space_after = Pt(2)
    return table


def _add_page_number(paragraph):
    paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = paragraph.add_run("Page ")
    _font_run(run, size=8, color=COLORS["muted"])
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instruction = OxmlElement("w:instrText")
    instruction.set(qn("xml:space"), "preserve")
    instruction.text = "PAGE"
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.extend([begin, instruction, end])


def _configure_document(doc: Document):
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.75)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)
    section.header_distance = Inches(0.35)
    section.footer_distance = Inches(0.35)

    styles = doc.styles
    normal = styles["Normal"]
    normal.font.name = "Arial"
    normal._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    normal.font.size = Pt(9.5)
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.1
    for style_name, size, color, before, after in (
        ("Heading 1", 16, COLORS["blue"], 16, 8),
        ("Heading 2", 13, COLORS["blue"], 12, 6),
        ("Heading 3", 11, COLORS["navy"], 8, 4),
    ):
        style = styles[style_name]
        style.font.name = "Arial"
        style._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        style.font.size = Pt(size)
        style.font.color.rgb = RGBColor.from_string(color)
        style.font.bold = True
        style.paragraph_format.space_before = Pt(before)
        style.paragraph_format.space_after = Pt(after)

    header_p = section.header.paragraphs[0]
    _set_paragraph_text(
        header_p,
        "Bilingual Translation and Regulatory Consistency Review",
        size=8,
        bold=True,
        color=COLORS["muted"],
    )
    footer_p = section.footer.paragraphs[0]
    _add_page_number(footer_p)


def _landscape_section(doc: Document):
    section = doc.add_section()
    section.orientation = WD_ORIENT.LANDSCAPE
    section.page_width = Inches(11)
    section.page_height = Inches(8.5)
    section.top_margin = Inches(0.65)
    section.bottom_margin = Inches(0.65)
    section.left_margin = Inches(0.55)
    section.right_margin = Inches(0.55)
    section.header_distance = Inches(0.3)
    section.footer_distance = Inches(0.3)
    section.header.is_linked_to_previous = True
    section.footer.is_linked_to_previous = True
    return section


def _summary_counts(result: ProcessingResult) -> dict[str, int]:
    all_findings = result.translation_findings + result.regulatory_findings
    pair_statuses = Counter(pair.pair_status for pair in result.pairs)
    return {
        "Blocks": len(result.blocks),
        "Confirmed pairs": pair_statuses.get("confirmed", 0),
        "Uncertain / unpaired": sum(
            count for status, count in pair_statuses.items() if status != "confirmed"
        ),
        "Confirmed findings": len(all_findings) + len(result.terminology_issues),
        "Critical": sum(f.severity == Severity.critical for f in all_findings),
        "Major": sum(f.severity == Severity.major for f in all_findings),
        "Minor": sum(f.severity == Severity.minor for f in all_findings)
        + sum(i.severity == Severity.minor for i in result.terminology_issues),
        "Observation": sum(f.severity == Severity.observation for f in all_findings),
    }


def generate_report(
    result: ProcessingResult,
    output_path: str | Path,
    *,
    ai_model: str = "Dry run / deterministic checks",
) -> Path:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    doc = Document()
    _configure_document(doc)

    # Editorial cover with restrained regulatory styling.
    for _ in range(5):
        doc.add_paragraph()
    kicker = doc.add_paragraph()
    kicker.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_paragraph_text(
        kicker, "AI-ASSISTED REVIEW REPORT", size=10, bold=True, color=COLORS["blue"]
    )
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_paragraph_text(
        title,
        "Bilingual Translation and Regulatory\nConsistency Review Report",
        size=24,
        bold=True,
        color=COLORS["navy"],
    )
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_paragraph_text(
        subtitle,
        result.metadata.filename,
        size=12,
        color=COLORS["muted"],
    )
    doc.add_paragraph()
    metadata_rows = [
        ["Review date", result.metadata.processed_at.astimezone().strftime("%Y-%m-%d %H:%M %Z")],
        ["Pages processed", str(result.metadata.page_count)],
        ["AI model", ai_model],
        ["Review mode", "Dry run" if result.settings.dry_run else "AI-assisted"],
    ]
    _add_table(doc, ["Report field", "Value"], metadata_rows, [1.5, 4.8], font_size=9)
    warning = doc.add_paragraph()
    _set_paragraph_text(warning, DISCLAIMER, size=9, bold=True, color="9B1C1C")

    doc.add_page_break()
    doc.add_heading("1. Executive summary", level=1)
    counts = _summary_counts(result)
    _add_table(
        doc,
        ["Metric", "Count"],
        [[key, str(value)] for key, value in counts.items()],
        [3.3, 3.0],
        font_size=9,
    )
    risk_text = (
        "Critical or major observations are present and should be prioritized for qualified manual review."
        if counts["Critical"] or counts["Major"]
        else "No critical or major deterministic observations were produced; this does not establish compliance."
    )
    p = doc.add_paragraph()
    _set_paragraph_text(p, f"Overall risk summary: {risk_text}", size=10, bold=True)
    p = doc.add_paragraph()
    _set_paragraph_text(
        p,
        "Detected regulations: "
        + (", ".join(reg.name for reg in result.regulations) or "None detected"),
        size=9.5,
    )

    doc.add_heading("2. Detected regulations and standards", level=1)
    _add_table(
        doc,
        ["Name", "Version", "Evidence", "Page", "Section", "Confidence"],
        [
            [
                reg.name,
                reg.version,
                compact_context(reg.evidence_text, 300),
                str(reg.page),
                reg.section or "",
                f"{reg.confidence:.0%}",
            ]
            for reg in result.regulations
        ],
        [1.4, 0.7, 2.9, 0.45, 0.55, 0.6],
        font_size=7.5,
    )

    doc.add_heading("3. Pairing quality summary", level=1)
    pair_statuses = Counter(pair.pair_status for pair in result.pairs)
    _add_table(
        doc,
        ["Status", "Count"],
        [[status, str(count)] for status, count in sorted(pair_statuses.items())],
        [3.3, 3.0],
        font_size=9,
    )
    _add_table(
        doc,
        ["Pairing method", "Count"],
        [
            [method, str(count)]
            for method, count in sorted(
                Counter(pair.pairing_method for pair in result.pairs).items()
            )
        ],
        [3.3, 3.0],
        font_size=9,
    )
    p = doc.add_paragraph()
    _set_paragraph_text(
        p,
        "Configured thresholds: confirmed "
        f"{result.settings.confirmed_pair_threshold:.0%}; uncertain "
        f"{result.settings.uncertain_pair_threshold:.0%}. "
        "Only confirmed pairs explicitly marked for translation checking can produce "
        "translation-equivalence findings.",
        size=9,
    )

    _landscape_section(doc)
    doc.add_heading("4. Translation equivalence findings", level=1)
    _add_table(
        doc,
        [
            "ID",
            "Pg",
            "Section",
            "Chinese text",
            "English text",
            "Issue type",
            "Severity",
            "Explanation",
            "Suggested correction",
            "Confidence",
        ],
        [
            [
                f.finding_id,
                str(f.page),
                f.section or "",
                compact_context(f.chinese_text, 420),
                compact_context(f.english_text, 420),
                f.issue_type,
                f.severity.value,
                f.explanation,
                "EN: "
                + (f.suggested_english or "-")
                + "\nZH: "
                + (f.suggested_chinese or "-"),
                f"{f.confidence:.0%}",
            ]
            for f in result.translation_findings
        ],
        [0.65, 0.3, 0.45, 1.45, 1.45, 0.75, 0.55, 1.75, 1.45, 0.5],
        font_size=6.7,
        severity_column=6,
    )

    doc.add_heading("5. Regulation consistency coverage matrix", level=1)
    coverage_rows = build_regulatory_coverage_matrix(
        result.pairs, result.regulations, result.regulatory_findings
    )
    _add_table(
        doc,
        [
            "Regulation clause",
            "Regulation topic",
            "Company section(s)",
            "Pages",
            "Coverage decision",
            "Severity",
            "Gap / missing content",
            "Mapped evidence",
            "Recommended action",
        ],
        [
            [
                row["Regulation clause/subsection"],
                row["Regulation topic"],
                row["Company file chapter/subsection"],
                row["Page references"],
                row["Coverage decision"],
                row["Severity"],
                row["Gap / missing content"],
                compact_context(row["Mapped evidence"], 430),
                row["Recommended action"],
            ]
            for row in coverage_rows
        ],
        [0.65, 1.15, 0.8, 0.45, 0.8, 0.5, 1.45, 1.65, 1.35],
        font_size=6.5,
        severity_column=5,
    )

    doc.add_heading("6. Regulatory consistency findings", level=1)
    _add_table(
        doc,
        [
            "ID",
            "Regulation",
            "Clause/topic",
            "Decision",
            "Pg",
            "Section",
            "Chinese text",
            "English text",
            "Issue",
            "Severity",
            "Gap/concern",
            "Recommendation",
            "Manual review",
        ],
        [
            [
                f.finding_id,
                f.regulation,
                f.clause_or_topic,
                f.decision,
                str(f.page),
                f.section or "",
                compact_context(f.chinese_text, 260),
                compact_context(f.english_text, 260),
                f.issue,
                f.severity.value,
                f.gap_or_concern,
                f.recommendation,
                (
                    "Yes"
                    + (f": {f.manual_review_reason}" if f.manual_review_reason else "")
                    if f.manual_review_required
                    else "No"
                ),
            ]
            for f in result.regulatory_findings
        ],
        [0.5, 0.85, 0.75, 0.7, 0.3, 0.4, 1.05, 1.05, 1.15, 0.5, 1.0, 1.2, 0.75],
        font_size=6.7,
        severity_column=9,
    )

    doc.add_heading("7. Terminology consistency findings", level=1)
    _add_table(
        doc,
        [
            "Chinese term",
            "English variants found",
            "Preferred English",
            "Locations",
            "Severity",
            "Recommendation",
        ],
        [
            [
                issue.chinese_term,
                "; ".join(issue.english_variants),
                issue.preferred_english,
                "; ".join(
                    f"p.{loc.page} {loc.section or ''}".strip()
                    for loc in issue.locations
                ),
                issue.severity.value,
                issue.recommendation,
            ]
            for issue in result.terminology_issues
        ],
        [1.2, 2.1, 1.8, 1.2, 0.7, 3.0],
        font_size=7.5,
        severity_column=4,
    )

    doc.add_heading("8. Unpaired / uncertain blocks for manual review", level=1)
    low_pairs = [
        pair
        for pair in result.pairs
        if pair.pair_status != "confirmed" or pair.needs_manual_review
    ]
    _add_table(
        doc,
        [
            "Page",
            "Section",
            "Content type",
            "Chinese",
            "Machine translation",
            "English / unpaired text",
            "Pair status",
            "Reason",
            "Confidence",
        ],
        [
            [
                str(pair.page),
                pair.section or "",
                str(pair.block_type),
                compact_context(pair.chinese_text, 400),
                compact_context(pair.machine_translated_english, 400),
                compact_context(pair.english_text or pair.unpaired_text, 400),
                pair.pair_status,
                pair.pairing_reason,
                f"{pair.pair_confidence:.0%}",
            ]
            for pair in low_pairs
        ],
        [0.35, 0.45, 0.75, 1.65, 1.65, 1.65, 0.7, 2.25, 0.55],
        font_size=6.8,
    )

    doc.add_heading("9. Extraction / OCR uncertainty", level=1)
    warnings = result.metadata.warnings + result.processing_warnings
    if not warnings:
        warnings = ["No extraction warnings were recorded."]
    for warning_text in warnings:
        p = doc.add_paragraph(style="List Bullet")
        _set_paragraph_text(p, warning_text, size=8.5)

    doc.add_heading("10. Disclaimer", level=1)
    p = doc.add_paragraph()
    _set_paragraph_text(p, DISCLAIMER, size=9.5, bold=True, color="9B1C1C")

    doc.save(output)
    return output
